@startuml

class PlatformWritePort
{
    ---
}
PlatformWritePort --|> Port

class PlatformReadPort
{
    ---
}
PlatformReadPort --|> Port

class PlatformSystem
{
    ---
}
PlatformSystem --|> SystemBase


@enduml