@startuml

class JobType
{
    + JobType(std::string name, uint32_t id)
     * @brief : Construct a new JobType object with the specified parameters
     * @param name : The name of the job type
     * @param id : A unique identifier for the job type

    + ~JobType() = default

    + std::string_view GetName() const
     * @brief : Get the name of the job type
     * @return std::string_view : The name of the job type

    + uint32_t GetID() const
     * @brief : Get the unique identifier of the job type
     * @return uint32_t : The unique identifier of the job type

    ---
    - std::string name_
     * The name of the job type, used for identification and categorization

    - uint32_t id_
     * A unique identifier for the job type, used for efficient lookup and management
}

class JobState
{
    + JobState(std::weak_ptr<bool> is_completed, std::condition_variable& condition, std::mutex& mutex)
     * @brief : Construct a new JobState object with the specified job type and completion status
     * @param is_completed : A weak pointer to a boolean that indicates whether the job has been completed
     * @param condition : A reference to a condition variable
     * @param mutex : A reference to a mutex to protect access to the job's completion status and condition variable

    + ~JobState() = default

    + bool IsCompleted() const
     * @brief : Check if the job has been completed
     * @return bool : True if the job is completed, false otherwise

    + bool WaitForCompletion() const
     * @brief : Wait for the job to be completed and return the completion status
     * @return bool : True if the job is completed, false otherwise

    - void NotifyCompletion()
     * @brief : Notify any waiting threads that the job has been completed
     * @note : This method should be called by the worker thread
    ---
    - std::weak_ptr<bool> is_completed_
     * A weak pointer to a boolean that indicates whether the job has been completed

    - std::condition_variable cv_
     * A reference to a condition variable that can be used to wait for the job's completion status to change

    - std::mutex mutex_
     * A mutex to protect access to the job's completion status and condition variable
}
JobState ..> Job

class Job
{
    + Job(JobType type, std::function<void()> job_func)
     * @brief : Construct a new Job object with the specified job type and function to execute
     * @param type : The type of the job
     * @param job_func : The function that represents the work to be done by the job

    + ~Job() = default

    + JobState GetState() const
     * @brief : Get the current state of the job
     * @return JobState : The current state of the job

    + JobType GetType() const
     * @brief : Get the type of the job
     * @return JobType : The type of the job

    + void Execute()
     * @brief : Execute the job's function and update the completion status
     * @note : This method should be called by the worker thread that is processing the job
    ---
    - JobType type_
     * The type of the job, which can be used for categorization and scheduling

    - std::function<void()> job_fun_
     * The function that represents the work to be done by the job

    - std::shared_ptr<bool> is_completed_
     * A shared pointer to a boolean that indicates whether the job has been completed
}
Job *-- JobType
Job *-- JobState

class WorkerThread
{
    + WorkerThread()
     * @brief : Create a new worker thread that will process jobs from the job queue
    
    + ~WorkerThread()
     * @brief : Signal the worker thread to stop and join it

    + uint32_t GetID() const
     * @brief : Get the unique identifier of the worker thread
     * @return uint32_t : The unique identifier of the worker thread

    + JobState DispatchJob(Job job)
     * @brief : Dispatch a job to be executed by the worker thread
     * @param job : The job to be executed
     * @return JobState : The state of the dispatched job

    + bool IsIdle() const
     * @brief : Check if the worker thread is currently idle (not processing a job)
     * @return bool : True if the worker thread is idle, false otherwise

    + JobType GetWorkingJobType() const
     * @brief : Get the type of job that the worker thread is currently processing
     * @return JobType : The type of job being processed, or a default value if the worker thread is idle

    - void Work()
     * @brief : The main loop of the worker thread that continuously checks for new jobs to process
    ---
    - uint32_t id_
     * A unique identifier for the worker thread, used for tracking and management

    - std::thread thread_
     * The actual thread object that runs the worker loop

    - std::mutex mutex_
     * A mutex to protect access to the worker thread's state

    - std::condition_variable condition_
     * A condition variable to signal the worker thread when a new job is dispatched

    - JobType current_job_type_
     * The type of job currently being processed by the worker thread, or a default value if idle
}
WorkerThread ..> Job
WorkerThread ..> JobState

class WorkerThreadProvider
{
    + WorkerThreadProvider() = default

    + ~WorkerThreadProvider()
     * @brief : Clean up all worker threads managed by the provider

    + uint32_t GetCpuCoreCount() const
     * @brief : Get the number of CPU cores available on the system
     * @return uint32_t : The number of CPU cores

    + uint32_t GetWorkerThreadCount() const
     * @brief : Get the total number of worker threads currently managed by the provider
     * @return uint32_t : The total number of worker threads

    + bool CreateWorkerThread()
     * @brief : Create a new worker thread that will execute the provided job function
     * @param jobFunction : The function to be executed by the worker thread
     * @return bool : True if the worker thread was successfully created, false otherwise

    + bool CreateWorkerThreads(uint32_t count)
     * @brief : Create multiple worker threads that will execute the provided job function
     * @param count : The number of worker threads to create
     * @return bool : True if all worker threads were successfully created, false otherwise

    + WorkerThread* GetIdleWorkerThread()
     * @brief : Get an idle worker thread from the pool
     * @return WorkerThread* : A pointer to an idle worker thread, or nullptr if no idle threads are available

    + std::vector<const WorkerThread*> GetIdleWorkerThreads() const
     * @brief : Get a list of all currently idle worker threads
     * @return std::vector<const WorkerThread*> : A vector of pointers to the currently idle worker threads
     * @note : The returned worker threads should not be modified by the caller

    + std::vector<const WorkerThread*> GetRunningWorkerThreads() const
     * @brief : Get a list of all currently running worker threads
     * @return std::vector<const WorkerThread*> : A vector of pointers to the currently running worker threads
     * @note : The returned worker threads should not be modified by the caller
    ---
    - std::vector<WorkerThread> worker_threads_
     * A vector that holds all the worker threads managed by the provider

    - std::vector<const WorkerThread*> running_threads_
     * A vector that holds pointers to the currently running worker threads

    - std::vector<const WorkerThread*> idle_threads_
     * A vector that holds pointers to the currently idle worker threads
}
WorkerThreadProvider *-- WorkerThread

class JobScheduler
{
    + JobScheduler(WorkerThreadProvider& worker_thread_provider)
     * @brief : Construct a new JobScheduler object with the specified worker thread provider

    + ~JobScheduler()

    + JobState ScheduleJob(Job job)
     * @brief : Schedule a job to be executed by an idle worker thread
     * @param job : The job to be scheduled
     * @return JobState : The state of the scheduled job (e.g., pending, running, completed)
    ---
    - WorkerThreadProvider& worker_thread_provider_
     * A reference to the worker thread provider that manages the worker threads used for executing jobs
}
JobScheduler *-- WorkerThreadProvider

class JobExecutionInfo
{
    + JobExecutionInfo(uint32_t worker_thread_id, JobType job_type)
     * @brief : Construct a new JobExecutionInfo object with the specified worker thread ID and job type
     * @param worker_thread_id : The ID of the worker thread that is processing the job
     * @param job_type : The type of the job being processed

    + ~JobExecutionInfo() = default

    + uint32_t GetWorkerThreadID() const
     * @brief : Get the ID of the worker thread that is processing the job
     * @return uint32_t : The ID of the worker thread

    + JobType GetJobType() const
     * @brief : Get the type of the job being processed
     * @return JobType : The type of the job being processed
    ---
    - uint32_t worker_thread_id_
     *  The worker thread ID which processes the job

    - JobType job_type_
     *  The type of the job being processed
}

class JobTracker
{
    + JobTracker(WorkerThreadProvider& worker_thread_provider)
     * @brief : Construct a new JobTracker object with the specified worker thread provider

    + ~JobTracker() = default

    + std::vector<JobExecutionInfo> GetRunningJobInfos() const
     * @brief : Get a list of all currently running job execution information
     * @return std::vector<JobExecutionInfo> : A vector of JobExecutionInfo objects representing the currently running jobs
    ---
    - WorkerThreadProvider& worker_thread_provider_
     * A reference to the worker thread provider that manages the worker threads used for executing jobs
}
JobTracker ..> WorkerThreadProvider
JobTracker ..> JobExecutionInfo


@enduml