@startuml

class NonCopyable
{
    * Copy Prohibited Mix-in

    + NonCopyable() = default
    + ~NonCopyable() = default
    + NonCopyable(const NonCopyable&) = delete
    + NonCopyable& operator=(const NonCopyable&) = delete
}

class Singleton
{
    * Template class for creating singleton instances of a given type

    + Singleton()
     * @brief : Construct a new Singleton object with the default constructor of the type T
     * Cast to accommodate offset changes during multiple inheritance

    + ~Singleton()
     * @brief : Clean up the singleton instance

    + {static} T& GetInstance()
     * @brief : Get the singleton instance of type T
     * @return T& : Reference to the singleton instance of type T
    
    + {static} bool IsInstantiated()
     * @brief : Check if the singleton instance has been instantiated
     * @return true : If the singleton instance has been instantiated
     * @return false : If the singleton instance has not been instantiated
    ---
    - {static} inline T* instance_ = nullptr
     * @brief : Static pointer to hold the singleton instance of type T
}
NonCopyable <|-- Singleton

@enduml