@startuml

class EntityHandle
{
    * Handle class for managing an entity in the world
    * Provides convenient methods to interact with the entity's components

    + EntityHandle(World& world, Entity entity)
    * @brief : Construct a new EntityHandle object with the given world and entity
    * @param world : Reference to the world that contains the entity
    * @param entity : The entity that this handle will manage

    + ~EntityHandle() = default
     * @brief : No special cleanup is needed for the EntityHandle object    
    
    + bool IsValid() const
    * @brief : Check if the entity associated with this handle is valid
    * @return : true if the entity is valid, false otherwise

    + bool Commit()
    * @brief : Commit the entity associated with this handle to the world
    * @return : true if the commit was successful, false otherwise

    + bool AddComponent(uint32_t component_id, std::unique_ptr<Component> component)
    * @brief : Wrap the AddComponent method of the World class for this entity
    * @param component_id : The ID of the component type to add
    * @param component : A unique pointer to the component instance to add
    * @return : true if the component was added successfully, false otherwise

    + bool AddComponent(std::unique_ptr<Component::Config> config)
    * @brief : Wrap the templated AddComponent method of the World class for this entity
    * @param config : A unique pointer to the component configuration to add
    * @return : true if the component was added successfully, false otherwise

    + bool RemoveComponent(uint32_t component_id)
    * @brief : Wrap the RemoveComponent method of the World class for this entity
    * @param component_id : The ID of the component type to remove
    * @return : true if the component was removed successfully, false otherwise
}

@enduml