@startuml

class JobState
{
    ---
}
JobState --> Job

class Job
{
    + JobState GetState() const
     * @brief : Get the current state of the job
     * @return JobState : The current state of the job (e.g., pending, running, completed)
    ---
}

class WorkerThread
{
    + WorkerThread()
     * @brief : Create a new worker thread that will process jobs from the job queue
    
    + ~WorkerThread()
     * @brief : Signal the worker thread to stop and join it

    + bool DispatchJob(Job job)
     * @brief : Dispatch a job to be executed by the worker thread
     * @param job : The job to be executed
     * @return bool : True if the job was successfully dispatched, false if the worker thread is already running a job

    + bool IsIdle() const
     * @brief : Check if the worker thread is currently idle (not processing a job)
     * @return bool : True if the worker thread is idle, false otherwise

    - void Work()
     * @brief : The main loop of the worker thread that continuously checks for new jobs to process
    ---
}

class WorkerThreadProvider
{
    + WorkerThreadProvider() = default
    + ~WorkerThreadProvider() = default

    + uint32_t GetCpuCoreCount() const
     * @brief : Get the number of CPU cores available on the system
     * @return uint32_t : The number of CPU cores

    + bool CreateWorkerThread()
     * @brief : Create a new worker thread that will execute the provided job function
     * @param jobFunction : The function to be executed by the worker thread
     * @return bool : True if the worker thread was successfully created, false otherwise

    + bool CreateWorkerThreads(uint32_t count)
     * @brief : Create multiple worker threads that will execute the provided job function
     * @param count : The number of worker threads to create
     * @return bool : True if all worker threads were successfully created, false otherwise

    + WorkerThread* GetIdleWorkerThread()
     * @brief : Get an idle worker thread from the pool
     * @return WorkerThread* : A pointer to an idle worker thread, or nullptr if no idle threads are available
    ---
    - std::vector<WorkerThread> running_threads_
     * @brief : A vector that holds the currently running worker threads

    - std::vector<WorkerThread> idle_threads_
     * @brief : A vector that holds the currently idle worker threads
}
WorkerThreadProvider *-- WorkerThread

class JobScheduler
{
    + JobScheduler()
     * @brief : Create a new worker thread provider and initialize the job scheduler

    + ~JobScheduler()

    + JobState ScheduleJob(Job job)
     * @brief : Schedule a job to be executed by an idle worker thread
     * @param job : The job to be scheduled
     * @return JobState : The state of the scheduled job (e.g., pending, running, completed)
    ---
    - WorkerThreadProvider worker_thread_provider_
     * @brief : The provider that manages the worker threads for executing jobs
}
JobScheduler *-- WorkerThreadProvider


@enduml